name: mesaybawi
description: تطبيق مسيباوي - منصة شاملة لخدمات النقل والمواصلات والطعام مع تتبع الموقع والحجوزات
publish_to: "none"
version: 1.0.1+2

homepage: https://mesibawy.com
repository: https://github.com/mesibawy/transportation-app

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  intl: ^0.20.2
  http: ^1.1.0
  connectivity_plus: ^7.0.0
  url_launcher: ^6.2.2
  badges: ^3.1.2 
  
  
  # Firebase - نسخ متوافقة مع بعض
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  cloud_firestore: ^6.0.1
  firebase_database: ^12.0.1
  firebase_auth: ^6.0.2
  firebase_storage: ^13.0.1
  flutter_secure_storage: ^9.0.0
  # الإشعارات المحلية
  flutter_local_notifications: ^19.4.2

  # Location and maps
  geolocator: ^14.0.2
  geocoding: ^3.0.0
  google_maps_flutter: ^2.5.0

  # UI and utilities
  cached_network_image: ^3.3.0
  image_picker: ^1.0.4
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
