name: Build Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. سحب الكود من GitHub
      - uses: actions/checkout@v3

      # 2. تثبيت Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0' # ضع نسخة Flutter الخاصة بك

      # 3. تثبيت الحزم
      - name: Install dependencies
        run: flutter pub get

      # 4. بناء APK
      - name: Build APK
        run: flutter build apk --release

      # 5. رفع الـ APK كـ Artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
